# Color-related functions for term/console applications.
#
# Terminal apps can use 5 different palettes:
#     1. Monochrome (2-color)
#     2. Low color (8-color)
#     3. ANSI / XTerm color (16-color)
#     4. High color (256-color)
#     5. TrueColor (16M-color/24-bit color)
module TermColors
  VERSION = "1.0.1"

  # Storage cache for `#match` method
  CACHE_MATCH = {} of Int32 => Int32

  # Upper bound on `CACHE_MATCH`. Key is the full 24-bit RGB value, so an
  # animated TrueColor source can feed `#match` unbounded distinct keys; on
  # overflow the cache is cleared wholesale.
  CACHE_MATCH_LIMIT = 65_536

  # 16 XTerm Colors.
  #
  # (Values taken from X11 sources, mapped to RGB, converted to hex.)
  Xterm = {
    "#000000", # black
    "#cd0000", # red3
    "#00cd00", # green3
    "#cdcd00", # yellow3
    "#0000ee", # blue2
    "#cd00cd", # magenta3
    "#00cdcd", # cyan3
    "#e5e5e5", # gray90
    "#7f7f7f", # gray50
    "#ff0000", # red
    "#00ff00", # green
    "#ffff00", # yellow
    "#5c5cff", # rgb:5c/5c/ff
    "#ff00ff", # magenta
    "#00ffff", # cyan
    "#ffffff", # white
  }

  # Mapping of notable color names to 16 color indices.
  ColorNames = {
    # XXX see if eventually strings can be replaced with symbols, here and elsewhere in similar case
    # special
    "default" => -1,
    "normal"  => -1,
    "bg"      => -1,
    "fg"      => -1,
    # normal
    "black"   => 0,
    "red"     => 1,
    "green"   => 2,
    "yellow"  => 3,
    "blue"    => 4,
    "magenta" => 5,
    "cyan"    => 6,
    "white"   => 7,
    # light
    "lightblack"   => 8,
    "lightred"     => 9,
    "lightgreen"   => 10,
    "lightyellow"  => 11,
    "lightblue"    => 12,
    "lightmagenta" => 13,
    "lightcyan"    => 14,
    "lightwhite"   => 15,
    # bright
    "brightblack"   => 8,
    "brightred"     => 9,
    "brightgreen"   => 10,
    "brightyellow"  => 11,
    "brightblue"    => 12,
    "brightmagenta" => 13,
    "brightcyan"    => 14,
    "brightwhite"   => 15,
    # alternate spellings
    "grey"       => 8,
    "gray"       => 8,
    "lightgrey"  => 7,
    "lightgray"  => 7,
    "brightgrey" => 7,
    "brightgray" => 7,
  }

  # Mapping of high color (256) indices to low color (8) indices.
  # Generated by `bin/generate_colors.rb`.
  HI2LI = [0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7, 0, 4, 4, 4, 4, 4, 2, 6, 4, 4, 4, 4, 2, 2, 6, 4, 4, 4, 2, 2, 2, 6, 4, 4, 2, 2, 2, 2, 6, 4, 2, 2, 2, 2, 2, 6, 1, 5, 4, 4, 4, 4, 3, 0, 4, 4, 4, 4, 2, 2, 6, 4, 4, 4, 2, 2, 2, 6, 4, 4, 2, 2, 2, 2, 6, 4, 2, 2, 2, 2, 2, 6, 1, 1, 5, 4, 4, 4, 1, 1, 5, 4, 4, 4, 3, 3, 0, 4, 4, 4, 2, 2, 2, 6, 4, 4, 2, 2, 2, 2, 6, 4, 2, 2, 2, 2, 2, 6, 1, 1, 1, 5, 4, 4, 1, 1, 1, 5, 4, 4, 1, 1, 1, 5, 4, 4, 3, 3, 3, 7, 4, 4, 2, 2, 2, 2, 6, 4, 2, 2, 2, 2, 2, 6, 1, 1, 1, 1, 5, 4, 1, 1, 1, 1, 5, 4, 1, 1, 1, 1, 5, 4, 1, 1, 1, 1, 5, 4, 3, 3, 3, 3, 7, 4, 2, 2, 2, 2, 2, 6, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 5, 1, 1, 1, 1, 1, 5, 3, 3, 3, 3, 3, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

  # Mapping of high color (256) indices to low color (8) names.
  # Generated by `bin/generate_colors.rb`.
  HI2LN = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white", "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white", "black", "blue", "blue", "blue", "blue", "blue", "green", "cyan", "blue", "blue", "blue", "blue", "green", "green", "cyan", "blue", "blue", "blue", "green", "green", "green", "cyan", "blue", "blue", "green", "green", "green", "green", "cyan", "blue", "green", "green", "green", "green", "green", "cyan", "red", "magenta", "blue", "blue", "blue", "blue", "yellow", "black", "blue", "blue", "blue", "blue", "green", "green", "cyan", "blue", "blue", "blue", "green", "green", "green", "cyan", "blue", "blue", "green", "green", "green", "green", "cyan", "blue", "green", "green", "green", "green", "green", "cyan", "red", "red", "magenta", "blue", "blue", "blue", "red", "red", "magenta", "blue", "blue", "blue", "yellow", "yellow", "black", "blue", "blue", "blue", "green", "green", "green", "cyan", "blue", "blue", "green", "green", "green", "green", "cyan", "blue", "green", "green", "green", "green", "green", "cyan", "red", "red", "red", "magenta", "blue", "blue", "red", "red", "red", "magenta", "blue", "blue", "red", "red", "red", "magenta", "blue", "blue", "yellow", "yellow", "yellow", "white", "blue", "blue", "green", "green", "green", "green", "cyan", "blue", "green", "green", "green", "green", "green", "cyan", "red", "red", "red", "red", "magenta", "blue", "red", "red", "red", "red", "magenta", "blue", "red", "red", "red", "red", "magenta", "blue", "red", "red", "red", "red", "magenta", "blue", "yellow", "yellow", "yellow", "yellow", "white", "blue", "green", "green", "green", "green", "green", "cyan", "red", "red", "red", "red", "red", "magenta", "red", "red", "red", "red", "red", "magenta", "red", "red", "red", "red", "red", "magenta", "red", "red", "red", "red", "red", "magenta", "red", "red", "red", "red", "red", "magenta", "yellow", "yellow", "yellow", "yellow", "yellow", "white", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "black", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white", "white"]

  # Mapping of high color (256) indices to hex color values.
  # Ported from the xterm color generation script (xterm defaults). Generated
  # by `bin/generate_colors_2.js`.
  HI2HH = ["#000000", "#cd0000", "#00cd00", "#cdcd00", "#0000ee", "#cd00cd", "#00cdcd", "#e5e5e5", "#7f7f7f", "#ff0000", "#00ff00", "#ffff00", "#5c5cff", "#ff00ff", "#00ffff", "#ffffff", "#000000", "#00005f", "#000087", "#0000af", "#0000d7", "#0000ff", "#005f00", "#005f5f", "#005f87", "#005faf", "#005fd7", "#005fff", "#008700", "#00875f", "#008787", "#0087af", "#0087d7", "#0087ff", "#00af00", "#00af5f", "#00af87", "#00afaf", "#00afd7", "#00afff", "#00d700", "#00d75f", "#00d787", "#00d7af", "#00d7d7", "#00d7ff", "#00ff00", "#00ff5f", "#00ff87", "#00ffaf", "#00ffd7", "#00ffff", "#5f0000", "#5f005f", "#5f0087", "#5f00af", "#5f00d7", "#5f00ff", "#5f5f00", "#5f5f5f", "#5f5f87", "#5f5faf", "#5f5fd7", "#5f5fff", "#5f8700", "#5f875f", "#5f8787", "#5f87af", "#5f87d7", "#5f87ff", "#5faf00", "#5faf5f", "#5faf87", "#5fafaf", "#5fafd7", "#5fafff", "#5fd700", "#5fd75f", "#5fd787", "#5fd7af", "#5fd7d7", "#5fd7ff", "#5fff00", "#5fff5f", "#5fff87", "#5fffaf", "#5fffd7", "#5fffff", "#870000", "#87005f", "#870087", "#8700af", "#8700d7", "#8700ff", "#875f00", "#875f5f", "#875f87", "#875faf", "#875fd7", "#875fff", "#878700", "#87875f", "#878787", "#8787af", "#8787d7", "#8787ff", "#87af00", "#87af5f", "#87af87", "#87afaf", "#87afd7", "#87afff", "#87d700", "#87d75f", "#87d787", "#87d7af", "#87d7d7", "#87d7ff", "#87ff00", "#87ff5f", "#87ff87", "#87ffaf", "#87ffd7", "#87ffff", "#af0000", "#af005f", "#af0087", "#af00af", "#af00d7", "#af00ff", "#af5f00", "#af5f5f", "#af5f87", "#af5faf", "#af5fd7", "#af5fff", "#af8700", "#af875f", "#af8787", "#af87af", "#af87d7", "#af87ff", "#afaf00", "#afaf5f", "#afaf87", "#afafaf", "#afafd7", "#afafff", "#afd700", "#afd75f", "#afd787", "#afd7af", "#afd7d7", "#afd7ff", "#afff00", "#afff5f", "#afff87", "#afffaf", "#afffd7", "#afffff", "#d70000", "#d7005f", "#d70087", "#d700af", "#d700d7", "#d700ff", "#d75f00", "#d75f5f", "#d75f87", "#d75faf", "#d75fd7", "#d75fff", "#d78700", "#d7875f", "#d78787", "#d787af", "#d787d7", "#d787ff", "#d7af00", "#d7af5f", "#d7af87", "#d7afaf", "#d7afd7", "#d7afff", "#d7d700", "#d7d75f", "#d7d787", "#d7d7af", "#d7d7d7", "#d7d7ff", "#d7ff00", "#d7ff5f", "#d7ff87", "#d7ffaf", "#d7ffd7", "#d7ffff", "#ff0000", "#ff005f", "#ff0087", "#ff00af", "#ff00d7", "#ff00ff", "#ff5f00", "#ff5f5f", "#ff5f87", "#ff5faf", "#ff5fd7", "#ff5fff", "#ff8700", "#ff875f", "#ff8787", "#ff87af", "#ff87d7", "#ff87ff", "#ffaf00", "#ffaf5f", "#ffaf87", "#ffafaf", "#ffafd7", "#ffafff", "#ffd700", "#ffd75f", "#ffd787", "#ffd7af", "#ffd7d7", "#ffd7ff", "#ffff00", "#ffff5f", "#ffff87", "#ffffaf", "#ffffd7", "#ffffff", "#080808", "#121212", "#1c1c1c", "#262626", "#303030", "#3a3a3a", "#444444", "#4e4e4e", "#585858", "#626262", "#6c6c6c", "#767676", "#808080", "#8a8a8a", "#949494", "#9e9e9e", "#a8a8a8", "#b2b2b2", "#bcbcbc", "#c6c6c6", "#d0d0d0", "#dadada", "#e4e4e4", "#eeeeee"]

  # Mapping of high color (256) indices to RGB color values.
  # Ported from the xterm color generation script (xterm defaults). Generated
  # by `bin/generate_colors_2.js`.
  HI2RGB = [{0, 0, 0}, {205, 0, 0}, {0, 205, 0}, {205, 205, 0}, {0, 0, 238}, {205, 0, 205}, {0, 205, 205}, {229, 229, 229}, {127, 127, 127}, {255, 0, 0}, {0, 255, 0}, {255, 255, 0}, {92, 92, 255}, {255, 0, 255}, {0, 255, 255}, {255, 255, 255}, {0, 0, 0}, {0, 0, 95}, {0, 0, 135}, {0, 0, 175}, {0, 0, 215}, {0, 0, 255}, {0, 95, 0}, {0, 95, 95}, {0, 95, 135}, {0, 95, 175}, {0, 95, 215}, {0, 95, 255}, {0, 135, 0}, {0, 135, 95}, {0, 135, 135}, {0, 135, 175}, {0, 135, 215}, {0, 135, 255}, {0, 175, 0}, {0, 175, 95}, {0, 175, 135}, {0, 175, 175}, {0, 175, 215}, {0, 175, 255}, {0, 215, 0}, {0, 215, 95}, {0, 215, 135}, {0, 215, 175}, {0, 215, 215}, {0, 215, 255}, {0, 255, 0}, {0, 255, 95}, {0, 255, 135}, {0, 255, 175}, {0, 255, 215}, {0, 255, 255}, {95, 0, 0}, {95, 0, 95}, {95, 0, 135}, {95, 0, 175}, {95, 0, 215}, {95, 0, 255}, {95, 95, 0}, {95, 95, 95}, {95, 95, 135}, {95, 95, 175}, {95, 95, 215}, {95, 95, 255}, {95, 135, 0}, {95, 135, 95}, {95, 135, 135}, {95, 135, 175}, {95, 135, 215}, {95, 135, 255}, {95, 175, 0}, {95, 175, 95}, {95, 175, 135}, {95, 175, 175}, {95, 175, 215}, {95, 175, 255}, {95, 215, 0}, {95, 215, 95}, {95, 215, 135}, {95, 215, 175}, {95, 215, 215}, {95, 215, 255}, {95, 255, 0}, {95, 255, 95}, {95, 255, 135}, {95, 255, 175}, {95, 255, 215}, {95, 255, 255}, {135, 0, 0}, {135, 0, 95}, {135, 0, 135}, {135, 0, 175}, {135, 0, 215}, {135, 0, 255}, {135, 95, 0}, {135, 95, 95}, {135, 95, 135}, {135, 95, 175}, {135, 95, 215}, {135, 95, 255}, {135, 135, 0}, {135, 135, 95}, {135, 135, 135}, {135, 135, 175}, {135, 135, 215}, {135, 135, 255}, {135, 175, 0}, {135, 175, 95}, {135, 175, 135}, {135, 175, 175}, {135, 175, 215}, {135, 175, 255}, {135, 215, 0}, {135, 215, 95}, {135, 215, 135}, {135, 215, 175}, {135, 215, 215}, {135, 215, 255}, {135, 255, 0}, {135, 255, 95}, {135, 255, 135}, {135, 255, 175}, {135, 255, 215}, {135, 255, 255}, {175, 0, 0}, {175, 0, 95}, {175, 0, 135}, {175, 0, 175}, {175, 0, 215}, {175, 0, 255}, {175, 95, 0}, {175, 95, 95}, {175, 95, 135}, {175, 95, 175}, {175, 95, 215}, {175, 95, 255}, {175, 135, 0}, {175, 135, 95}, {175, 135, 135}, {175, 135, 175}, {175, 135, 215}, {175, 135, 255}, {175, 175, 0}, {175, 175, 95}, {175, 175, 135}, {175, 175, 175}, {175, 175, 215}, {175, 175, 255}, {175, 215, 0}, {175, 215, 95}, {175, 215, 135}, {175, 215, 175}, {175, 215, 215}, {175, 215, 255}, {175, 255, 0}, {175, 255, 95}, {175, 255, 135}, {175, 255, 175}, {175, 255, 215}, {175, 255, 255}, {215, 0, 0}, {215, 0, 95}, {215, 0, 135}, {215, 0, 175}, {215, 0, 215}, {215, 0, 255}, {215, 95, 0}, {215, 95, 95}, {215, 95, 135}, {215, 95, 175}, {215, 95, 215}, {215, 95, 255}, {215, 135, 0}, {215, 135, 95}, {215, 135, 135}, {215, 135, 175}, {215, 135, 215}, {215, 135, 255}, {215, 175, 0}, {215, 175, 95}, {215, 175, 135}, {215, 175, 175}, {215, 175, 215}, {215, 175, 255}, {215, 215, 0}, {215, 215, 95}, {215, 215, 135}, {215, 215, 175}, {215, 215, 215}, {215, 215, 255}, {215, 255, 0}, {215, 255, 95}, {215, 255, 135}, {215, 255, 175}, {215, 255, 215}, {215, 255, 255}, {255, 0, 0}, {255, 0, 95}, {255, 0, 135}, {255, 0, 175}, {255, 0, 215}, {255, 0, 255}, {255, 95, 0}, {255, 95, 95}, {255, 95, 135}, {255, 95, 175}, {255, 95, 215}, {255, 95, 255}, {255, 135, 0}, {255, 135, 95}, {255, 135, 135}, {255, 135, 175}, {255, 135, 215}, {255, 135, 255}, {255, 175, 0}, {255, 175, 95}, {255, 175, 135}, {255, 175, 175}, {255, 175, 215}, {255, 175, 255}, {255, 215, 0}, {255, 215, 95}, {255, 215, 135}, {255, 215, 175}, {255, 215, 215}, {255, 215, 255}, {255, 255, 0}, {255, 255, 95}, {255, 255, 135}, {255, 255, 175}, {255, 255, 215}, {255, 255, 255}, {8, 8, 8}, {18, 18, 18}, {28, 28, 28}, {38, 38, 38}, {48, 48, 48}, {58, 58, 58}, {68, 68, 68}, {78, 78, 78}, {88, 88, 88}, {98, 98, 98}, {108, 108, 108}, {118, 118, 118}, {128, 128, 128}, {138, 138, 138}, {148, 148, 148}, {158, 158, 158}, {168, 168, 168}, {178, 178, 178}, {188, 188, 188}, {198, 198, 198}, {208, 208, 208}, {218, 218, 218}, {228, 228, 228}, {238, 238, 238}]

  # Takes color value and returns index of the nearest/closest matching color in the current palette.
  def match(r1 : String)
    hex = r1
    if hex[0] != '#'
      raise "Color value must start with '#'"
    end
    hex = hex_to_rgb(hex)
    r1 = hex[0]; g1 = hex[1]; b1 = hex[2]
    match r1, g1, b1
  end

  # :ditto:
  def match(r1 : Array)
    b1 = r1[2]; g1 = r1[1]; r1 = r1[0]
    match r1, g1, b1
  end

  # :ditto:
  def match(r1 : Tuple)
    match *r1
  end

  # :ditto:
  def match(r1 : Int, g1 : Int, b1 : Int)
    hash : Int32 = (r1 << 16) | (g1 << 8) | b1

    # Single hash probe on the cache-hit path; old `has_key?` + `[]` probed twice.
    CACHE_MATCH.fetch(hash) do
      # ldiff = Float64::INFINITY
      ldiff = Int32::MAX # Match type of `CACHE_MATCH` above.
      li = -1
      i = 0

      while i < HI2RGB.size
        c = HI2RGB[i]
        r2 = c[0]
        g2 = c[1]
        b2 = c[2]

        diff = color_distance(r1, g1, b1, r2, g2, b2)

        if diff == 0
          li = i
          break
        end

        if diff < ldiff
          ldiff = diff
          li = i
        end
        i += 1
      end

      CACHE_MATCH.clear if CACHE_MATCH.size >= CACHE_MATCH_LIMIT
      CACHE_MATCH[hash] = li
    end
  end

  # Converts RGB to hex color value (#color)
  def rgb_to_hex(r : Array)
    rgb_to_hex r[0], r[1], r[2]
  end

  # :ditto:
  #
  # Lets `#rgb_to_hex` compose with `#hex_to_rgb` (its inverse), which returns
  # a `Tuple` — e.g. `rgb_to_hex(hex_to_rgb(x))`.
  def rgb_to_hex(r : Tuple)
    rgb_to_hex r[0], r[1], r[2]
  end

  # :ditto:
  def rgb_to_hex(r : Colorize::ColorRGB)
    rgb_to_hex r.red, r.green, r.blue
  end

  # :ditto:
  def rgb_to_hex(r, g, b)
    "#" + to_hex2(r) + to_hex2(g) + to_hex2(b)
  end

  # Converts number to hex value with 2 places.
  def to_hex2(n)
    n = n.to_s 16
    if n.size < 2
      n = "0" + n
    end
    n
  end

  # Converts number to hex value with 4 places.
  def to_hex4(n)
    n = n.to_s 16
    while n.size < 4
      n = "0" + n
    end
    n
  end

  # Converts hex color value (#col or #color) to {r,g,b}.
  def hex_to_rgb(hex : String)
    if hex.size == 4
      # Converts #abc into #aabbcc
      hex = hex[0].to_s + hex[1] + hex[1] + hex[2] + hex[2] + hex[3] + hex[3]
    end
    col = hex[1..-1].to_i 16
    r = (col >> 16) & 0xff
    g = (col >> 8) & 0xff
    b = col & 0xff
    {r, g, b}
  end

  # Finds color similarity (weighted Euclidean distance, no color-space
  # conversion needed). See http:#stackoverflow.com/questions/1633828
  def color_distance(r1, g1, b1, r2, g2, b2)
    dr = 30 &* (r1 - r2)
    dg = 59 &* (g1 - g2)
    db = 11 &* (b1 - b2)
    (dr &* dr) &+ (dg &* dg) &+ (db &* db)
  end

  # Mixes two 24-bit RGB colors in RGB space. `alpha` is the opacity/weight of
  # `c1` (1.0 keeps `c1` fully, 0.0 yields `c2`, 0.5 is the midpoint). Returns a
  # `0xRRGGBB` value.
  #
  # Operates directly in RGB (TrueColor); consumers blend at full precision and
  # only reduce on output.
  def mix(c1 : Int, c2 : Int, alpha = 0.5) : Int32
    r1, g1, b1 = unpack_rgb(c1)
    r2, g2, b2 = unpack_rgb(c2)

    # Per-channel blend `c1 + (c2 - c1) * (1 - alpha)`, computed in fixed point.
    # `(1 - alpha)` is materialized once as a 16-bit fixed-point integer
    # (0..65536), so each channel computation is integer multiply + shift
    # instead of float multiply + truncation. Output differs from the float
    # path by at most one step per channel — visually identical. This is the
    # per-cell compositing path (shadows, tints, plane blends), so avoiding
    # float ops matters.
    w = ((1.0 - alpha) * 65536).to_i
    w = 0 if w < 0
    w = 65536 if w > 65536

    r = (r1 + (((r2 - r1) * w) >> 16)) & 0xff
    g = (g1 + (((g2 - g1) * w) >> 16)) & 0xff
    b = (b1 + (((b2 - b1) * w) >> 16)) & 0xff

    (r << 16) | (g << 8) | b
  end

  # `0xRRGGBB` -> `{h (0..360), s (0..1), l (0..1)}`. HSL counterpart of the HSV
  # pair below; used to lighten/darken perceptually evenly (lightness is a
  # single axis in HSL), compute relative luminance, etc.
  def rgb_to_hsl(rgb : Int32) : Tuple(Float64, Float64, Float64)
    r, g, b = unpack_rgb_f(rgb)
    # Branch-pick max/min directly instead of `{r, g, b}.max/.min` (tuple
    # reduction); ~9% faster, identical results.
    max = r > g ? (r > b ? r : b) : (g > b ? g : b)
    min = r < g ? (r < b ? r : b) : (g < b ? g : b)
    l = (max + min) / 2.0
    if max == min
      return {0.0, 0.0, l} # achromatic
    end
    d = max - min
    s = l > 0.5 ? d / (2.0 - max - min) : d / (max + min)
    h = case max
        when r then (g - b) / d + (g < b ? 6.0 : 0.0)
        when g then (b - r) / d + 2.0
        else        (r - g) / d + 4.0
        end
    {(h * 60.0), s, l}
  end

  # `{h, s, l}` -> `0xRRGGBB` (inverse of `#rgb_to_hsl`).
  def hsl_to_rgb(h : Float64, s : Float64, l : Float64) : Int32
    h = h % 360.0
    h += 360.0 if h < 0
    if s <= 0.0
      v = clamp_byte(l * 255.0)
      return (v << 16) | (v << 8) | v
    end
    c = (1.0 - (2.0 * l - 1.0).abs) * s
    x = c * (1.0 - ((h / 60.0) % 2.0 - 1.0).abs)
    m = l - c / 2.0
    # `h` is already wrapped into `0...360`, so flooring `h / 60` yields the
    # same sextant `0..5` the explicit ranges used to select.
    r, g, b = sextant_rgb((h / 60.0).to_i, c, x)
    (clamp_byte((r + m) * 255.0) << 16) |
      (clamp_byte((g + m) * 255.0) << 8) |
      clamp_byte((b + m) * 255.0)
  end

  # Moves a color's lightness by *delta* (positive = lighter, negative = darker),
  # clamped to `[0, 1]`. Saturation/hue are preserved (the work happens in HSL).
  def adjust_lightness(rgb : Int32, delta : Float64) : Int32
    h, s, l = rgb_to_hsl(rgb)
    hsl_to_rgb(h, s, (l + delta).clamp(0.0, 1.0))
  end

  # Lightens *rgb* by *amount* (`0..1`) of lightness.
  def lighten(rgb : Int32, amount : Float64) : Int32
    adjust_lightness(rgb, amount.abs)
  end

  # Darkens *rgb* by *amount* (`0..1`) of lightness.
  def darken(rgb : Int32, amount : Float64) : Int32
    adjust_lightness(rgb, -amount.abs)
  end

  # Relative luminance (sRGB-weighted, `0..1`) — how *bright* a color reads, used
  # to choose a contrasting foreground.
  def luminance(rgb : Int32) : Float64
    r, g, b = unpack_rgb_f(rgb)
    0.2126 * r + 0.7152 * g + 0.0722 * b
  end

  # Picks whichever of *dark*/*light* contrasts better against *bg*.
  def readable_on(bg : Int32, dark : Int32, light : Int32) : Int32
    luminance(bg) > 0.5 ? dark : light
  end

  # `0xRRGGBB` -> `"#rrggbb"`.
  def hex(rgb : Int32) : String
    "#%06x" % (rgb & 0xFFFFFF)
  end

  # Rounds and clamps a channel value into `0..255` (shared by the HSL math).
  private def clamp_byte(value : Float64) : Int32
    value.round.to_i.clamp(0, 255)
  end

  # Unpacks a packed `0xRRGGBB` integer into its `{r, g, b}` byte channels.
  # Shared by `#mix`/`#sgr_color`.
  private def unpack_rgb(rgb : Int) : Tuple(Int32, Int32, Int32)
    {(rgb >> 16) & 0xff, (rgb >> 8) & 0xff, rgb & 0xff}
  end

  # Unpacks a packed `0xRRGGBB` integer into its `{r, g, b}` channels normalized
  # to `0.0..1.0`. Shared by `#rgb_to_hsl`/`#luminance`.
  private def unpack_rgb_f(rgb : Int) : Tuple(Float64, Float64, Float64)
    r, g, b = unpack_rgb(rgb)
    {r / 255.0, g / 255.0, b / 255.0}
  end

  # Maps a hue *sextant* (`0..5`) and precomputed chroma components *c*/*x* to
  # the `{r, g, b}` channel arrangement for that 60-degree slice of the color
  # wheel. Shared by `#hsl_to_rgb` and `#hsv_i`, which only differ in deriving the sextant.
  private def sextant_rgb(sextant : Int, c : Float64, x : Float64) : Tuple(Float64, Float64, Float64)
    case sextant
    when 0 then {c, x, 0.0}
    when 1 then {x, c, 0.0}
    when 2 then {0.0, c, x}
    when 3 then {0.0, x, c}
    when 4 then {x, 0.0, c}
    else        {c, 0.0, x}
    end
  end

  # Converts an HSV color to a packed `0xRRGGBB` integer (24-bit RGB).
  #
  # *h* is a hue in degrees (wrapped into `0..360`); *s* and *v* are saturation
  # and value in `0.0..1.0`. Allocation-free counterpart of `#hsv`.
  def hsv_i(h : Int | Float, s : Float64 = 1.0, v : Float64 = 1.0) : Int32
    hh = h.to_f % 360.0
    hh += 360.0 if hh < 0
    c = v * s
    x = c * (1 - (((hh / 60.0) % 2) - 1).abs)
    m = v - c
    rf, gf, bf = sextant_rgb((hh.to_i // 60) % 6, c, x)
    # Round via `clamp_byte` rather than truncate: `.to_i` floors, biasing up to
    # one step too dark, and disagrees with `hsl_to_rgb` which already rounds.
    r = clamp_byte((rf + m) * 255)
    g = clamp_byte((gf + m) * 255)
    b = clamp_byte((bf + m) * 255)
    (r << 16) | (g << 8) | b
  end

  # Converts an HSV color to a `#rrggbb` hex string.
  #
  # *h* is a hue in degrees (wrapped into `0..360`); *s* and *v* are saturation
  # and value in `0.0..1.0`. Defaults give full saturation/brightness. For the
  # allocation-free packed-integer form, see `#hsv_i`.
  def hsv(h : Int | Float, s : Float64 = 1.0, v : Float64 = 1.0) : String
    hex hsv_i(h, s, v)
  end

  # Converts color into lower/smaller color space.
  #
  # ```
  # reduce(color, @tput.colors)
  # ```
  def reduce(color, total)
    # Independent `if`s (not `elsif`): reducing to 2 colors requires first
    # collapsing a high color into the 8-color range (256->8->2).
    if color >= 16 && total <= 16
      color = HI2LI[color]
    end
    if color >= 8 && total <= 8
      color -= 8
    end
    if color >= 2 && total <= 2
      color %= 2
    end
    color
  end

  # Parses a color spec into the native color value: `-1` for the terminal
  # default, or a 24-bit `0xRRGGBB` integer.
  #
  # NOTE: native color space is TrueColor; reduction to a smaller palette
  # happens only at output time (see `sgr_color`).
  def convert(color : Int)
    # Already a native color value (`-1` or `0xRRGGBB`).
    color
  end

  # :ditto:
  def convert(color : String)
    # Most specs ("#ff8800", "white") contain no separators; only pay for the
    # regex rewrite when a `-` or ` ` is present.
    if color.includes?('-') || color.includes?(' ')
      color = color.gsub(/[\- ]/, "")
    end
    # Only parse as hex when well-formed `#rgb`/`#rrggbb`; `convert` must
    # degrade to the terminal default (`-1`) for malformed specs, same as for
    # unknown names and unsupported types.
    return hex_to_int color if hex_color? color
    if idx = ColorNames[color]?
      return idx == -1 ? -1 : hex_to_int(Xterm[idx])
    end
    -1
  end

  # :ditto:
  #
  # `Tuple` and `Array` share one body: both index with `[](Int)` and yield
  # `.to_i`-able elements, so one method packs either form of `{r, g, b}`.
  def convert(color : Tuple | Array)
    (color[0].to_i << 16) | (color[1].to_i << 8) | color[2].to_i
  end

  # :nodoc:
  def convert(color)
    -1
  end

  # True only for a syntactically valid `#rgb`/`#rrggbb` hex color. Lets
  # `#convert` reject malformed specs before they reach the raising hex parser.
  private def hex_color?(s : String) : Bool
    return false unless (s.size == 4 || s.size == 7) && s.starts_with?('#')
    (1...s.size).all? { |i| s[i].to_i?(16) }
  end

  # Converts a hex color value (`#abc` or `#rrggbb`) to a 24-bit `0xRRGGBB`
  # integer.
  def hex_to_int(hex : String) : Int32
    r, g, b = hex_to_rgb hex
    (r << 16) | (g << 8) | b
  end

  # Maps a 256-color palette index to its native 24-bit `0xRRGGBB` value (used
  # when parsing incoming `38;5;n`/ANSI SGR codes into the RGB-native form).
  def palette_to_rgb(idx : Int) : Int32
    # Guard `idx >= 0` explicitly: Crystal's `Array#[]?` treats a negative index
    # as an offset from the end (`HI2RGB[-1]?` returns the last entry, not
    # `nil`), which would silently yield the wrong color instead of `0`.
    if idx >= 0 && (c = HI2RGB[idx]?)
      (c[0] << 16) | (c[1] << 8) | c[2]
    else
      0
    end
  end

  # Builds the SGR parameter fragment encoding one color for a terminal that
  # supports `colors` colors, choosing the richest encoding that fits:
  # TrueColor (`38;2;r;g;b`), 256-color (`38;5;n`), or 16/8-color ANSI
  # (`30..37`/`90..97`). `color` is a native color (`-1` for default, or
  # `0xRRGGBB`); `fg` selects foreground (38/3x/9x) vs background (48/4x/10x).
  def sgr_color(color : Int, fg : Bool, colors : Int) : String
    return fg ? "39" : "49" if color == -1

    r, g, b = unpack_rgb(color)

    if colors >= 0x1000000
      return "#{fg ? 38 : 48};2;#{r};#{g};#{b}"
    end

    idx = reduce(match(r, g, b), colors)
    if idx < 8
      (fg ? 30 + idx : 40 + idx).to_s
    elsif idx < 16
      (fg ? 90 + (idx - 8) : 100 + (idx - 8)).to_s
    else
      "#{fg ? 38 : 48};5;#{idx}"
    end
  end

  # Represents Colors class. Use when a class is preferred over a module.
  class Data
    include ::TermColors
  end
end
